insert into department values(1,'Chemistry',1);
insert into department values(2,'MCA',2);
insert into department values(3,'Computer Science',3);
insert into department values(4,'Mathematics',4);
insert into department values(5,'Physics',5);
insert into department values(6,'Zoology',6);
insert into department values(7,'Boytany',7);
insert into department values(8,'Anthropology',8);
insert into department values(9,'Geology',9);
insert into department values(10,'Histroy',10);
insert into department values(11,'MBA',11);
insert into department values(12,'Geography',12);
insert into department values(13,'Economics',13);
insert into department values(14,'Odia',14);
insert into department values(15,'Applied Mthemaics',15);
insert into department values(16,'Bio_Informetics',16);
insert into department values(17,'Applied_Physics',17);
